import {
  CollabEventsRecord,
  CPrimitive,
  InitToken,
  UpdateMeta,
} from "@collabs/core";
import {
  CRDTMessageMeta,
  CRDTMetaRequest,
  CRDTSavedStateMeta,
  CRuntime,
} from "../runtime";

/**
 * Convenience base class for a CRDT implementation that sends
 * its own messages over the network.
 *
 * Extend this class to implement a "primitive" CRDT with a simple
 * broadcast interface ([[sendCRDT]]/[[receiveCRDT]]) and no child
 * Collabs. This matches how most (op-based) CRDTs
 * are described algorithmically.
 *
 * This class differs from [[CPrimitive]] in that it requires [[CRuntime]],
 * and it makes it easier to work with [[CRuntime]]'s [[CRDTMessageMeta]].
 *
 * See also:
 * - [[CObject]], for an "object" Collab that does not need to send its own
 * messages.
 * - [[CPrimitive]], for general [[Collab]]s (not just CRDTs).
 */
export abstract class PrimitiveCRDT<
  Events extends CollabEventsRecord = CollabEventsRecord
> extends CPrimitive<Events> {
  constructor(init: InitToken) {
    super(init);

    if ((this.runtime as CRuntime).isCRDTRuntime !== true) {
      throw new Error("this.runtime must be CRuntime or similar");
    }
  }

  /**
   * Broadcasts a message to other replicas of this CRDT.
   * The message will be delivered to all replicas' [[receiveCRDT]],
   * including locally.
   *
   * Call this method instead of [[Collab.send]] or [[CPrimitive.sendPrimitive]].
   *
   * By default, [[receiveCRDT]]'s `crdtMeta` will contain all fields that are accessed
   * during the sender's local call to receiveCRDT.
   * You can request additional fields with `metaRequest`.
   *
   * @param message The message to send.
   */
  protected sendCRDT(
    message: Uint8Array | string,
    metaRequest?: CRDTMetaRequest
  ): void {
    super.sendPrimitive(message, metaRequest);
  }

  /**
   * Do not override; override [[receiveCRDT]] instead.
   */
  protected receivePrimitive(
    message: Uint8Array | string,
    meta: UpdateMeta
  ): void {
    this.receiveCRDT(message, meta, <CRDTMessageMeta>meta.runtimeExtra);
  }

  /**
   * Receives a message sent by [[sendCRDT]]
   * on a local or remote replica of this PrimitiveCRDT.
   *
   * This method processes the message, changes the
   * local state accordingly, and emits events describing the
   * local changes.
   *
   * This method may assume eventual, exactly-once, causal-order message
   * delivery, and it must ensure strong eventual consistency.
   *
   * See [[Collab.receive]].
   *
   * @param message The message sent by [[sendCRDT]].
   * @param meta Generic metadata attached to this message by the [[CRuntime]].
   * Note that `meta.updateType` is always `"message"`.
   * @param crdtMeta CRDT-specific Metadata attached to this message by the [[CRuntime]].
   * It contains all fields that were accessed
   * during the sender's local call to receiveCRDT,
   * plus requests made in [[sendCRDT]].
   */
  protected abstract receiveCRDT(
    message: Uint8Array | string,
    meta: UpdateMeta,
    crdtMeta: CRDTMessageMeta
  ): void;

  protected savePrimitive(): Uint8Array {
    return this.saveCRDT();
  }

  protected loadPrimitive(
    savedState: Uint8Array | null,
    meta: UpdateMeta
  ): void {
    this.loadCRDT(savedState, meta, <CRDTSavedStateMeta>meta.runtimeExtra);
  }

  /**
   * Returns saved state describing the current state of this Collab.
   *
   * The saved state may later be passed to [[loadCRDT]] on a replica of
   * this Collab, possibly in a different collaboration session,
   * with rules set by the [[runtime]]. For example, [[CRuntime]]
   * allows [[load]] to be called only at the beginning of a session,
   * before sending or receiving any messages.
   *
   * `saveCRDT` may be called at any time, possibly many times while an app
   * is running. Calling `saveCRDT` should not affect this Collab's
   * user-visible state.
   *
   * @return The saved state.
   */
  protected abstract saveCRDT(): Uint8Array;

  /**
   * Called by this Collab's parent to load some saved state.
   * You may assume that the saved state was generated by
   * [[saveCRDT]] on some replica of this Collab,
   * possibly in a different collaboration session,
   * with guarantees set by the [[runtime]].
   *
   * This method may also be called with `savedState = null`;
   * you should ignore such calls (i.e., return immediately)
   * *unless* you override [[canGC]]. If you do override `canGC`,
   * see that method's docs for instructions.
   *
   * @param savedState The saved state to load,
   * or `null` as described above.
   * @param meta Generic metadata attached to this message by the [[CRuntime]].
   * Note that `meta.updateType` is always `"savedState"`.
   * @param crdtMeta CRDT-specific Metadata attached to this message by the [[CRuntime]].
   * It contains all fields and vector clock entries.
   */
  protected abstract loadCRDT(
    savedState: Uint8Array | null,
    meta: UpdateMeta,
    crdtMeta: CRDTSavedStateMeta
  ): void;
}
